# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-20 13:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11, '手机号码必须为11位')])),
                ('password', models.CharField(max_length=32)),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('update_time', models.DateField(auto_now=True)),
                ('nickname', models.CharField(blank=True, max_length=200, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], default=1)),
                ('school', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('hometown', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
