# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-23 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('goodsName', models.CharField(max_length=30, verbose_name='商品名称')),
                ('photourl', models.ImageField(upload_to='banner/%y%m/%d', verbose_name='商品相册')),
                ('bannerOrder', models.SmallIntegerField()),
            ],
            options={
                'verbose_name': '首页轮播商品表',
                'verbose_name_plural': '首页轮播商品表',
                'db_table': 'BannerModel',
            },
        ),
        migrations.CreateModel(
            name='GoodsAlbumModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('photourl', models.ImageField(upload_to='goods/%y%m/%d', verbose_name='图片地址')),
            ],
            options={
                'verbose_name': '商品相册表',
                'verbose_name_plural': '商品相册表',
                'db_table': 'GoodsAlbumModel',
            },
        ),
        migrations.CreateModel(
            name='GoodsClassModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('classintro', models.TextField(max_length=40, verbose_name='分类简介')),
            ],
            options={
                'verbose_name': '商品分类信息',
                'verbose_name_plural': '商品分类信息',
                'db_table': 'GoodsClassModel',
            },
        ),
        migrations.CreateModel(
            name='GoodsskuClassModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('stock', models.PositiveIntegerField(verbose_name='库存')),
                ('goodslogo', models.ImageField(upload_to='goodslogo/%y%m/%d', verbose_name='商品logo')),
                ('shelves', models.BooleanField(choices=[(False, '未上架'), (True, '已上架')], verbose_name='是否上架')),
                ('goodsclass_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsClassModel', verbose_name='商品分类ID')),
            ],
            options={
                'verbose_name': '商品SKU表',
                'verbose_name_plural': '商品SKU表',
                'db_table': 'GoodsskuClassModel',
            },
        ),
        migrations.CreateModel(
            name='GoodsSPUModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('SPUname', models.CharField(max_length=50, verbose_name='spu名称')),
                ('SPUdetails', models.TextField(max_length=50, verbose_name='spu详情')),
            ],
            options={
                'verbose_name': '商品SPU表',
                'verbose_name_plural': '商品SPU表',
                'db_table': 'GoodsSPUModel',
            },
        ),
        migrations.CreateModel(
            name='GoodsUnitModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('unitname', models.CharField(max_length=10, verbose_name='单位名')),
            ],
            options={
                'verbose_name': '商品单位表',
                'verbose_name_plural': '商品单位表',
                'db_table': 'GoodsUnitModel',
            },
        ),
        migrations.CreateModel(
            name='HomeActarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
                ('desc', models.TextField(max_length=200, verbose_name='描述')),
                ('order', models.SmallIntegerField()),
                ('shelves', models.BooleanField(choices=[(False, '未上架'), (True, '已上架')], verbose_name='是否上架')),
                ('skuid', models.ManyToManyField(to='goods.GoodsskuClassModel', verbose_name='和商品sku多对多')),
            ],
            options={
                'verbose_name': '首页活动专区',
                'verbose_name_plural': '首页活动专区',
                'db_table': 'HomeActarea',
            },
        ),
        migrations.CreateModel(
            name='IndexActModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
                ('photourl', models.ImageField(upload_to='activity/%y%m/%d', verbose_name='活动图片')),
                ('url', models.CharField(max_length=100, verbose_name='url地址')),
            ],
            options={
                'verbose_name': '首页活动表',
                'verbose_name_plural': '首页活动表',
                'db_table': 'IndexActModel',
            },
        ),
        migrations.AddField(
            model_name='goodsskuclassmodel',
            name='goodsspu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsSPUModel', verbose_name='商品spu_id'),
        ),
        migrations.AddField(
            model_name='goodsskuclassmodel',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsUnitModel', verbose_name='单位'),
        ),
        migrations.AddField(
            model_name='goodsalbummodel',
            name='goodsSKUID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsskuClassModel', verbose_name='商品SKUID'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='goodsSKU',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsskuClassModel', verbose_name='商品SKUID'),
        ),
    ]
