# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-24 09:57
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20190123_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsspumodel',
            name='SPUdetails',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='spu详情'),
        ),
    ]
